files:
  - source: /**/res/values/strings.xml
    ignore:
      - example-
    translation: /**/res/values-%android_code%/%original_file_name%
  - source: /**/res/values-v23/strings.xml
    ignore:
      - example-
    translation: /**/res/values-%android_code%-v23/%original_file_name%