/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.android.apps.muzei.api;

import android.content.Context;
import android.content.Intent;
import android.database.Cursor;
import android.net.Uri;
import android.text.TextUtils;

import com.google.android.apps.muzei.api.provider.MuzeiArtProvider;

import java.net.URISyntaxException;
import java.util.Date;

import androidx.annotation.NonNull;

/**
 * A serializable object representing a single artwork retrieved from the
 * {@link MuzeiContract.Artwork} table.
 *
 * <p> Instances of this should only be created by using {@link Artwork#fromCursor(Cursor)}.
 */
@SuppressWarnings("deprecation")
public class Artwork {

    private String mComponentName;
    private Uri mImageUri;
    private String mTitle;
    private String mByline;
    private String mAttribution;
    private Intent mViewIntent;
    private Date mDateAdded;

    private Artwork() {
    }

    /**
     * Returns the authority of the art provider for this artwork.
     *
     * @return the authority of the {@link MuzeiArtProvider} providing this artwork.
     */
    public String getProviderAuthority() {
        return mComponentName;
    }

    /**
     * Returns the artwork's image URI.
     *
     * @return the artwork's image URI, or null if it doesn't have one.
     */
    public Uri getImageUri() {
        return mImageUri;
    }

    /**
     * Returns the artwork's user-visible title.
     *
     * @return the artwork's user-visible title, or null if it doesn't have one.
     */
    public String getTitle() {
        return mTitle;
    }

    /**
     * Returns the artwork's user-visible byline, usually containing the author and date.
     * This is generally used as a secondary source of information after the {@link #getTitle title}.
     *
     * @return the artwork's user-visible byline, or null if it doesn't have one.
     */
    public String getByline() {
        return mByline;
    }

    /**
     * Returns the artwork's user-visible attribution text.
     * This is generally used as a tertiary source of information after the
     * {@link #getTitle title} and the {@link #getByline byline}.
     *
     * @return the artwork's user-visible attribution text, or null if it doesn't have any.
     */
    public String getAttribution() {
        return mAttribution;
    }

    /**
     * Returns the activity {@link Intent} that will be started when the user clicks
     * for more details about the artwork. This should point to an exported
     * {@link android.app.Activity}. Muzei will automatically add
     * {@link Intent#FLAG_GRANT_READ_URI_PERMISSION} to allow reading any attached data URI,
     * but note that all extras will be lost when Muzei uses {@link Intent#toUri(int)}.
     *
     *
     * @return the activity {@link Intent} that will be
     * {@linkplain Context#startActivity(Intent) started} when the user clicks
     * for more details about the artwork, or null if the artwork doesn't have one.
     * @deprecated View Intents are no longer exposed outside of Muzei.
     */
    @Deprecated
    public Intent getViewIntent() {
        return mViewIntent;
    }

    /**
     * Returns when this artwork was added to Muzei. This is automatically generated by Muzei.
     *
     * @return when this artwork was added to Muzei.
     */
    public Date getDateAdded() {
        return mDateAdded;
    }

    /**
     * Sets the artwork's image URI.
     *
     * @param imageUri the artwork's image URI.
     * @deprecated Artwork should be considered immutable after creation.
     */
    @Deprecated
    public void setImageUri(Uri imageUri) {
        mImageUri = imageUri;
    }

    /**
     * Sets the artwork's user-visible title.
     *
     * @param title the artwork's user-visible title.
     * @deprecated Artwork should be considered immutable after creation.
     */
    @Deprecated
    public void setTitle(String title) {
        mTitle = title;
    }

    /**
     * Sets the artwork's user-visible byline, usually containing the author and date.
     * This is generally used as a secondary source of information after the {@link #setTitle} title}.
     *
     * @param byline the artwork's user-visible byline.
     * @deprecated Artwork should be considered immutable after creation.
     */
    @Deprecated
    public void setByline(String byline) {
        mByline = byline;
    }

    /**
     * Sets the artwork's user-visible attribution text.
     * This is generally used as a tertiary source of information after the
     * {@link #setTitle  title} and the {@link #setByline byline}.
     *
     * @param attribution the artwork's user-visible attribution text.
     * @deprecated Artwork should be considered immutable after creation.
     */
    @Deprecated
    public void setAttribution(String attribution) {
        mAttribution = attribution;
    }

    /**
     * Sets the activity {@link Intent} that will be
     * {@linkplain Context#startActivity(Intent) started} when
     * the user clicks for more details about the artwork.
     *
     * <p> The activity that this intent resolves to must have <code>android:exported</code>
     * set to <code>true</code>.
     *
     * <p> Muzei will automatically add {@link Intent#FLAG_GRANT_READ_URI_PERMISSION}
     * to allow reading any  attached data URI, but note that all extras will be lost
     * when Muzei uses {@link Intent#toUri(int)} to serialize the Intent.
     *
     * <p> Because artwork objects can be persisted across device reboots,
     * {@linkplain android.app.PendingIntent pending intents}, which would alleviate the
     * exported requirement, are not currently supported.
     *
     * @param viewIntent the activity {@link Intent} that will be
     *                   {@linkplain Context#startActivity(Intent) started} when the user clicks
     *                   for more details about the artwork.
     * @deprecated Artwork should be considered immutable after creation.
     */
    @Deprecated
    public void setViewIntent(Intent viewIntent) {
        mViewIntent = viewIntent;
    }

    /**
     * Sets when this artwork was added to Muzei. This will be done automatically for you.
     *
     * @param dateAdded when this artwork was added to Muzei.
     * @deprecated Artwork should be considered immutable after creation.
     */
    @Deprecated
    public void setDateAdded(Date dateAdded) {
        mDateAdded = dateAdded;
    }

    /**
     * A <a href="http://en.wikipedia.org/wiki/Builder_pattern">builder</a>-style, <a
     * href="http://en.wikipedia.org/wiki/Fluent_interface">fluent interface</a> for creating {@link
     * Artwork} objects. Example usage is below.
     *
     * <pre class="prettyprint">
     * Artwork artwork = new Artwork.Builder()
     *         .imageUri(Uri.parse("http://example.com/image.jpg"))
     *         .title("Example image")
     *         .byline("Unknown person, c. 1980")
     *         .attribution("Copyright (C) Unknown person, 1980")
     *         .viewIntent(new Intent(Intent.ACTION_VIEW,
     *                 Uri.parse("http://example.com/imagedetails.html")))
     *         .build();
     * </pre>
     *
     * The only required field is {@linkplain #imageUri(Uri) the image URI}, but you
     * should really provide all the metadata, especially title, byline, and view intent.
     * @deprecated Use {@link com.google.android.apps.muzei.api.provider.Artwork.Builder} with a
     * {@link MuzeiArtProvider}.
     */
    @SuppressWarnings({"deprecation", "DeprecatedIsStillUsed"})
    @Deprecated
    public static class Builder {
        private final Artwork mArtwork;

        /**
         * @deprecated Use {@link com.google.android.apps.muzei.api.provider.Artwork.Builder}
         * with a {@link MuzeiArtProvider}.
         */
        @Deprecated
        public Builder() {
            mArtwork = new Artwork();
        }

        /**
         * Sets the authority of the {@link MuzeiArtProvider} for this artwork.
         * This will automatically be set for you by Muzei.
         *
         * @param authority the authority of the {@link MuzeiArtProvider} for this artwork.
         *
         * @return this {@link Builder}.
         */
        @SuppressWarnings("UnusedReturnValue")
        Builder providerAuthority(String authority) {
            mArtwork.mComponentName = authority;
            return this;
        }

        /**
         * Sets the artwork's image URI, which must resolve to a JPEG or PNG image, ideally
         * under 5MB. Supported URI schemes are:
         *
         * <ul>
         * <li><code>content://...</code>. Content URIs must be public (i.e. not require
         * permissions). To build a file-based content provider, see the
         * <a href="https://developer.android.com/reference/android/support/v4/content/FileProvider.html">FileProvider</a>
         * class in the Android support library.</li>
         * <li><code>android.resource://...</code>. Resource URLs are recommended to be identified
         * by resource type name and entry name instead of resource ID, to be more reliable after
         * source app updates.</li>
         * <li><code>http://...</code> or <code>https://...</code>. These URLs must be
         * publicly accessible (i.e. not require authentication of any kind).</li>
         * </ul>
         *
         * While Muzei will download and cache the artwork, these URIs should be as long-lived as
         * possible, since in the event Muzei's cache is wiped out, it will attempt to fetch the
         * image again. Also, given that the device may not be connected to the network at the time
         * an artwork is added, the time the URI may be fetched significantly after the artwork
         * is published.
         *
         * @param imageUri the artwork's image URI
         *
         * @return this {@link Builder}.
         * @deprecated Use {@link com.google.android.apps.muzei.api.provider.Artwork.Builder}
         * with a {@link MuzeiArtProvider}.
         */
        @Deprecated
        public Builder imageUri(Uri imageUri) {
            mArtwork.mImageUri = imageUri;
            return this;
        }

        /**
         * Sets the artwork's user-visible title.
         *
         * @param title the artwork's user-visible title.
         *
         * @return this {@link Builder}.
         * @deprecated Use {@link com.google.android.apps.muzei.api.provider.Artwork.Builder}
         * with a {@link MuzeiArtProvider}.
         */
        @Deprecated
        public Builder title(String title) {
            mArtwork.mTitle = title;
            return this;
        }

        /**
         * Sets the artwork's user-visible byline, usually containing the author and date.
         * This is generally used as a secondary source of information after the {@link #title} title}.
         *
         * @param byline the artwork's user-visible byline.
         *
         * @return this {@link Builder}.
         * @deprecated Use {@link com.google.android.apps.muzei.api.provider.Artwork.Builder}
         * with a {@link MuzeiArtProvider}.
         */
        @Deprecated
        public Builder byline(String byline) {
            mArtwork.mByline = byline;
            return this;
        }

        /**
         * Sets the artwork's user-visible attribution text.
         * This is generally used as a tertiary source of information after the
         * {@link #setTitle  title} and the {@link #byline byline}.
         *
         * @param attribution the artwork's user-visible attribution text.
         *
         * @return this {@link Builder}.
         * @deprecated Use {@link com.google.android.apps.muzei.api.provider.Artwork.Builder}
         * with a {@link MuzeiArtProvider}.
         */
        @Deprecated
        public Builder attribution(String attribution) {
            mArtwork.mAttribution = attribution;
            return this;
        }

        /**
         * Sets the activity {@link Intent} that will be
         * {@linkplain Context#startActivity(Intent) started} when
         * the user clicks for more details about the artwork.
         *
         * <p> The activity that this intent resolves to must have <code>android:exported</code>
         * set to <code>true</code>.
         *
         * <p> Muzei will automatically add {@link Intent#FLAG_GRANT_READ_URI_PERMISSION}
         * to allow reading any  attached data URI, but note that all extras will be lost
         * when Muzei uses {@link Intent#toUri(int)} to serialize the Intent.
         *
         * <p> Because artwork objects can be persisted across device reboots,
         * {@linkplain android.app.PendingIntent pending intents}, which would alleviate the
         * exported requirement, are not currently supported.
         *
         * @param viewIntent the activity {@link Intent} that will be
         *                   {@linkplain Context#startActivity(Intent) started} when the user clicks
         *                   for more details about the artwork.
         *
         * @return this {@link Builder}.
         * @deprecated Use {@link com.google.android.apps.muzei.api.provider.Artwork.Builder}
         * with a {@link MuzeiArtProvider}.
         */
        @Deprecated
        public Builder viewIntent(Intent viewIntent) {
            mArtwork.mViewIntent = viewIntent;
            return this;
        }

        /**
         * Sets when this artwork was added to Muzei. This will be done automatically for you.
         *
         * @param dateAdded when this artwork was added to Muzei.
         *
         * @return this {@link Builder}.
         * @deprecated Use {@link com.google.android.apps.muzei.api.provider.Artwork.Builder}
         * with a {@link MuzeiArtProvider}.
         */
        @Deprecated
        public Builder dateAdded(Date dateAdded) {
            mArtwork.mDateAdded = dateAdded;
            return this;
        }

        /**
         * Creates and returns the final Artwork object. Once this method is called, it is not valid
         * to further use this {@link Artwork.Builder} object.
         *
         * @return the final constructed {@link Artwork}.
         * @deprecated Use {@link com.google.android.apps.muzei.api.provider.Artwork.Builder}
         * with a {@link MuzeiArtProvider}.
         */
        @Deprecated
        public Artwork build() {
            return mArtwork;
        }
    }

    /**
     * Deserializes an artwork object from a {@link Cursor} retrieved from
     * {@link com.google.android.apps.muzei.api.MuzeiContract.Artwork#CONTENT_URI}.
     *
     * @param cursor a {@link Cursor} retrieved from
     *               {@link com.google.android.apps.muzei.api.MuzeiContract.Artwork#CONTENT_URI},
     *               set at the correct position.
     *
     * @return the artwork from the current position of the Cursor.
     */
    @SuppressWarnings({"deprecation", "WeakerAccess"})
    @NonNull
    public static Artwork fromCursor(@NonNull Cursor cursor) {
        Builder builder = new Builder();
        int componentNameColumnIndex = cursor.getColumnIndex(MuzeiContract.Artwork.COLUMN_NAME_PROVIDER_AUTHORITY);
        if (componentNameColumnIndex != -1) {
            builder.providerAuthority(cursor.getString(componentNameColumnIndex));
        }
        int imageUriColumnIndex = cursor.getColumnIndex(MuzeiContract.Artwork.COLUMN_NAME_IMAGE_URI);
        if (imageUriColumnIndex != -1) {
            String uriString = cursor.getString(imageUriColumnIndex);
            if (!TextUtils.isEmpty(uriString)) {
                builder.imageUri(Uri.parse(uriString));
            }
        }
        int titleColumnIndex = cursor.getColumnIndex(MuzeiContract.Artwork.COLUMN_NAME_TITLE);
        if (titleColumnIndex != -1) {
            builder.title(cursor.getString(titleColumnIndex));
        }
        int bylineColumnIndex = cursor.getColumnIndex(MuzeiContract.Artwork.COLUMN_NAME_BYLINE);
        if (bylineColumnIndex != -1) {
            builder.byline(cursor.getString(bylineColumnIndex));
        }
        int attributionColumnIndex = cursor.getColumnIndex(MuzeiContract.Artwork.COLUMN_NAME_ATTRIBUTION);
        if (attributionColumnIndex != -1) {
            builder.attribution(cursor.getString(attributionColumnIndex));
        }
        int viewIntentColumnIndex = cursor.getColumnIndex(MuzeiContract.Artwork.COLUMN_NAME_VIEW_INTENT);
        if (viewIntentColumnIndex != -1) {
            try {
                String viewIntent = cursor.getString(viewIntentColumnIndex);
                if (!TextUtils.isEmpty(viewIntent)) {
                    builder.viewIntent(Intent.parseUri(viewIntent, Intent.URI_INTENT_SCHEME));
                }
            } catch (URISyntaxException ignored) {
            }
        }
        int dateAddedColumnIndex = cursor.getColumnIndex(MuzeiContract.Artwork.COLUMN_NAME_DATE_ADDED);
        if (dateAddedColumnIndex != -1) {
            builder.dateAdded(new Date(cursor.getLong(dateAddedColumnIndex)));
        }
        return builder.build();
    }
}
